SELECT 
    S.CODFILIAL AS FILIAL,

    -- Contagem distinta de cargas MAX (prefixo 5)
    COUNT(DISTINCT CASE WHEN SUBSTR(C.NUMCAR, 1, 1) = '5' THEN C.NUMCAR END) AS MAX,

    -- Contagem distinta de cargas WIN (prefixo 8)
    COUNT(DISTINCT CASE WHEN SUBSTR(C.NUMCAR, 1, 1) = '8' THEN C.NUMCAR END) AS WIN,

    -- Total de cargas distintas (MAX + WIN)
    COUNT(DISTINCT C.NUMCAR) AS TOTAL,

    -- Porcentagem de cargas MAX sobre TOTAL
    ROUND(
        (COUNT(DISTINCT CASE WHEN SUBSTR(C.NUMCAR, 1, 1) = '5' THEN C.NUMCAR END) * 100.0) 
        / NULLIF(COUNT(DISTINCT C.NUMCAR), 0), 
        2
    ) AS PCT_MAX_SOBRE_TOTAL

FROM PCCARREG C
JOIN PCNFSAID S ON C.NUMCAR = S.NUMCAR

WHERE C.DT_CANCEL IS NULL
  AND C.DTSAIDA BETWEEN TO_DATE('01/07/2025', 'DD/MM/YYYY') 
                    AND TO_DATE('31/07/2025', 'DD/MM/YYYY')
  AND (C.NUMCAR LIKE '8%' OR C.NUMCAR LIKE '5%')

GROUP BY S.CODFILIAL
ORDER BY S.CODFILIAL;
