/*SCRIPT PARA CONSULTAR CARREGAMENTOS MONTADOS SETANDO PERÍODOS*/
SELECT LPAD(S.CODFILIAL, 2, '0') AS CODFILIAL,
       COUNT(DISTINCT CASE WHEN SUBSTR(C.NUMCAR, 1, 1) = '8' THEN C.NUMCAR END) AS WIN,
       COUNT(DISTINCT CASE WHEN SUBSTR(C.NUMCAR, 1, 1) = '5' THEN C.NUMCAR END) AS MAX
  FROM PCCARREG C, PCNFSAID S
WHERE C.NUMCAR = S.NUMCAR
  --AND S.CODFILIAL = '04'
  AND C.DT_CANCEL IS NULL
  AND TRUNC(C.DATAMON) BETWEEN TO_DATE('01-07-2025', 'DD-MM-YYYY') AND TO_DATE('31-07-2025', 'DD-MM-YYYY')
  AND (C.NUMCAR LIKE '8%' OR C.NUMCAR LIKE '5%')
GROUP BY LPAD(S.CODFILIAL, 2, '0')
ORDER BY CODFILIAL;

/*SCRIPT PARA CONSULTAR CARREGAMENTOS EXPORTADOS PELO MAXROTEIRIZADOR*/
SELECT DT_CANCEL 
    FROM PCCARREG 
    WHERE 1 = 1 
    AND NUMCAR IN ()
    ORDER BY 1
;