WITH FORNECEDORES_LIGADOS AS (
    SELECT CODFORNEC
    FROM PCFORNEC
    WHERE CODFORNECPRINC = :FORNECEDOR_PRINCIPAL
),
PRODUTOS_FORNECEDOR AS (
    SELECT CODPROD
    FROM PCPRODUT
    WHERE CODFORNEC IN (SELECT CODFORNEC FROM FORNECEDORES_LIGADOS)
),
PRODUTOS_FORCA_VENDAS AS (
    SELECT DISTINCT PF.CODPROD
    FROM PCPRODFILIAL PF
    WHERE PF.ENVIARFORCAVENDAS = 'S'
),
PRODUTOS_COM_ESTOQUE AS (
    SELECT DISTINCT E.CODPROD
    FROM PCEST E
    WHERE E.QTEST > 0
),
PRODUTOS_VENDIDOS_ULT_3_MESES AS (
    SELECT DISTINCT M.CODPROD
    FROM PCMOV M
    WHERE M.DTMOV BETWEEN ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -3)
                      AND LAST_DAY(ADD_MONTHS(TRUNC(SYSDATE, 'MM'), 0))
),
PRODUTOS_VALIDOS AS (
    SELECT CODPROD
    FROM (
        SELECT CE.CODPROD
        FROM PRODUTOS_COM_ESTOQUE CE
        JOIN PRODUTOS_FORCA_VENDAS FV ON FV.CODPROD = CE.CODPROD
        UNION
        SELECT V.CODPROD
        FROM PRODUTOS_VENDIDOS_ULT_3_MESES V
        JOIN PRODUTOS_FORCA_VENDAS FV ON FV.CODPROD = V.CODPROD
    )
)
SELECT DISTINCT PF.CODPROD
FROM PRODUTOS_FORNECEDOR PF
JOIN PRODUTOS_VALIDOS PV ON PV.CODPROD = PF.CODPROD
ORDER BY PF.CODPROD;
