WITH PRODUTOS_FORNECEDOR AS (
    SELECT CODPROD
    FROM PCPRODUT
    WHERE CODFORNEC = :FORNECEDOR_ID
),
PRODUTOS_ATIVOS_ESTOQUE AS (
    SELECT DISTINCT E.CODPROD
    FROM PCEST E
    JOIN PCPRODFILIAL PF 
      ON PF.CODPROD = E.CODPROD 
     AND PF.CODFILIAL = E.CODFILIAL
    WHERE E.QTEST > 0 
      AND PF.ENVIARFORCAVENDAS = 'S'
),
PRODUTOS_VENDIDOS_ULT_3_MESES AS (
    SELECT DISTINCT M.CODPROD
    FROM PCMOV M
    WHERE M.DTMOV BETWEEN ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -3)
                      AND LAST_DAY(ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -1))
)
SELECT DISTINCT PF.CODPROD
FROM PRODUTOS_FORNECEDOR PF
JOIN PRODUTOS_ATIVOS_ESTOQUE PAE ON PAE.CODPROD = PF.CODPROD
JOIN PRODUTOS_VENDIDOS_ULT_3_MESES PVM ON PVM.CODPROD = PF.CODPROD
ORDER BY PF.CODPROD;